import {DiscountableItem, DiscountResult} from './types';

/**
 * Warning: This file is generated by the context mapper hooks generator.
 * Any changes to this file will be lost.
 */

/**
 * Represents a DiscountCalculation function definition
 *
 * This slug is used to generate JSON schema for validation purposes
 */
export type DiscountCalculationFunctionDefinition = {
  args: {
    discountable_item: DiscountableItem;
  };
  returns: DiscountResult;
};

/**
 * DiscountCalculation function
 *
 * @template C - The type of the function configuration
 * @param {C} configuration - Custom configuration data passed to the function
 * @param {DiscountableItem} discountable_item - discountable_item
 * @returns {DiscountResult} - DiscountCalculation result
 */
export type DiscountCalculationFunction<C> = (
  configuration: C,
  discountable_item: DiscountableItem,
) => DiscountResult;
