// Generated by ts-to-zod
import {z} from 'zod';

export const oneTimeSchema = z.object({
  type: z.literal('one_time'),
  at: z.date(),
});

export const timeRangeSchema = z.object({
  type: z.literal('time_range'),
  start_date: z.date(),
  end_date: z.date(),
});

export const anyTimeRangeSchema = z.union([oneTimeSchema, timeRangeSchema]);

export const currencySchema = z
  .string()
  .regex(
    /^(usd|aed|afn|all|amd|ang|aoa|ars|aud|awg|azn|bam|bbd|bdt|bgn|bhd|bif|bmd|bnd|bob|brl|bsd|bwp|byn|bzd|cad|cdf|chf|clp|cny|cop|crc|cve|czk|djf|dkk|dop|dzd|egp|etb|eur|fjd|fkp|gbp|gel|gip|gmd|gnf|gtq|gyd|hkd|hnl|hrk|htg|huf|idr|ils|inr|isk|jmd|jod|jpy|kes|kgs|khr|kmf|krw|kwd|kyd|kzt|lak|lbp|lkr|lrd|lsl|mad|mdl|mga|mkd|mmk|mnt|mop|mur|mvr|mwk|mxn|myr|mzn|nad|ngn|nio|nok|npr|nzd|omr|pab|pen|pgk|php|pkr|pln|pyg|qar|ron|rsd|rub|rwf|sar|sbd|scr|sek|sgd|shp|sle|sos|srd|std|szl|thb|tjs|tnd|top|try|ttd|twd|tzs|uah|ugx|uyu|uzs|vnd|vuv|wst|xaf|xcd|xcg|xof|xpf|yer|zar|zmw)$/i,
  );

export const monetaryAmountSchema = z.object({
  amount: z.number(),
  currency: currencySchema,
});

export const positiveMonetaryAmountSchema = z.object({
  amount: z.number().min(0),
  currency: currencySchema,
});

export const percentSchema = z.number().min(0).max(100);

export const decimalSchema = z.string();

export const metadataSchema = z.record(z.string());
